application: mon-pfe
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /statics
  static_dir: web/statics
  
- url: /.*
  secure: always
  script: main.application

libraries:

- name: webapp2
  version: latest
  
- name: jinja2
  version: latest
 
- name : django
  version: latest